
String mockUser(){
  return '''
[
  {
    "id": 0,
  "firstname": "Bradley",
  "lastname": "Hopper",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 10,
  "firstname": "Houston",
  "lastname": "Kelly",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 20,
  "firstname": "Ester",
  "lastname": "Pierce",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 30,
  "firstname": "Stark",
  "lastname": "Estes",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 40,
  "firstname": "Mathews",
  "lastname": "Giles",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 50,
  "firstname": "Nettie",
  "lastname": "Collier",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 60,
  "firstname": "Sanford",
  "lastname": "Powers",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 70,
  "firstname": "Manuela",
  "lastname": "Ewing",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 80,
  "firstname": "Tyson",
  "lastname": "Oneal",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 90,
  "firstname": "Malinda",
  "lastname": "Stout",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 100,
  "firstname": "Reese",
  "lastname": "Cameron",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 110,
  "firstname": "Cheri",
  "lastname": "Rhodes",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 120,
  "firstname": "Valerie",
  "lastname": "Randolph",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 130,
  "firstname": "Debra",
  "lastname": "Coleman",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 140,
  "firstname": "Workman",
  "lastname": "Gomez",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 150,
  "firstname": "Hatfield",
  "lastname": "Jackson",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true,
  },
  {
  "id": 160,
  "firstname": "Bond",
  "lastname": "Paul",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 170,
  "firstname": "Aileen",
  "lastname": "Rowland",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 180,
  "firstname": "Sullivan",
  "lastname": "Brown",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 190,
  "firstname": "Addie",
  "lastname": "Raymond",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 200,
  "firstname": "Beach",
  "lastname": "Wood",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 210,
  "firstname": "Cynthia",
  "lastname": "Johns",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 220,
  "firstname": "Annmarie",
  "lastname": "Hodge",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 230,
  "firstname": "Wolfe",
  "lastname": "Rutledge",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 240,
  "firstname": "Imogene",
  "lastname": "Welch",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 250,
  "firstname": "Gracie",
  "lastname": "Winters",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 260,
  "firstname": "Lolita",
  "lastname": "Lloyd",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 270,
  "firstname": "Tameka",
  "lastname": "Holcomb",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 280,
  "firstname": "Kellie",
  "lastname": "Bates",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 290,
  "firstname": "Santiago",
  "lastname": "Rose",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 300,
  "firstname": "Mccarty",
  "lastname": "Dawson",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 310,
  "firstname": "Bonita",
  "lastname": "Carver",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 320,
  "firstname": "Howard",
  "lastname": "Norton",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 330,
  "firstname": "Sophie",
  "lastname": "Briggs",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 340,
  "firstname": "Carolina",
  "lastname": "Dominguez",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "birthday": "Sun Jul 30 1995 02:39:42 GMT+0000 (UTC)",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 350,
  "firstname": "Barry",
  "lastname": "Adkins",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 360,
  "firstname": "Lilian",
  "lastname": "Gallegos",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 370,
  "firstname": "Anne",
  "lastname": "Osborn",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 380,
  "firstname": "Randi",
  "lastname": "Beard",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 390,
  "firstname": "Weeks",
  "lastname": "Hicks",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 400,
  "firstname": "Maynard",
  "lastname": "Hampton",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 410,
  "firstname": "Lane",
  "lastname": "Knox",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "birthday": "Wed Dec 25 2013 11:37:21 GMT+0000 (UTC)",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 420,
  "firstname": "Pansy",
  "lastname": "Lowe",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 430,
  "firstname": "Corine",
  "lastname": "Brady",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 440,
  "firstname": "Jasmine",
  "lastname": "Lee",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 450,
  "firstname": "Newman",
  "lastname": "Armstrong",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 460,
  "firstname": "Moreno",
  "lastname": "Marquez",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 470,
  "firstname": "Justine",
  "lastname": "Bradshaw",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 480,
  "firstname": "Patricia",
  "lastname": "Simmons",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 490,
  "firstname": "Chrystal",
  "lastname": "Hanson",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": false
  },
  {
  "id": 500,
  "firstname": "Jami",
  "lastname": "Bryan",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 510,
  "firstname": "Mccoy",
  "lastname": "Fernandez",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  },
  {
  "id": 520,
  "firstname": "Cabrera",
  "lastname": "Olson",
  "email_address": "example@live.com",
  "password": "ThisIsARandomNonScriptedPassWord",
  "address_id": 1,
  "survey_id": 1,
  "address_work": null,
  "isAdmin": true
  }
  ]''';
}